#!/bin/sh

#GSM
while [ ! -e /dev/ipa ]; do sleep 0.2; done
echo 1 > /dev/ipa

#WiFi
echo 1 > /sys/kernel/boot_wlan/boot_wlan

#Flashlight
chown phablet /sys/class/leds/led:torch_0/brightness
chown phablet /sys/class/leds/led:torch_1/brightness
chown phablet  /sys/class/leds/led:switch_0/brightness

#oFono workaround
while [ "$(systemctl is-active ofono)" != "active" ]; do sleep 0.5; done
sleep 10
systemctl restart ofono
